apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: database-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wiredbrain.labels" . | nindent 4 }}
    component: database
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: {{ .Values.azure.clientId | quote }}
    keyvaultName: {{ .Values.azure.keyVaultName | quote }}
    tenantId: {{ .Values.azure.tenantId | quote }}
    objects: |
      array:
        - |
          objectName: {{ .Values.secrets.postgresPassword }}
          objectType: secret
          objectVersion: ""
          objectAlias: postgres-password
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: products-api-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wiredbrain.labels" . | nindent 4 }}
    component: products-api
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: {{ .Values.azure.clientId | quote }}
    keyvaultName: {{ .Values.azure.keyVaultName | quote }}
    tenantId: {{ .Values.azure.tenantId | quote }}
    objects: |
      array:
        - |
          objectName: {{ .Values.secrets.applicationProperties }}
          objectType: secret
          objectVersion: ""
          objectAlias: application.properties
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: stock-api-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wiredbrain.labels" . | nindent 4 }}
    component: stock-api
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: {{ .Values.azure.clientId | quote }}
    keyvaultName: {{ .Values.azure.keyVaultName | quote }}
    tenantId: {{ .Values.azure.tenantId | quote }}
    objects: |
      array:
        - |
          objectName: {{ .Values.secrets.dbConnectionString }}
          objectType: secret
          objectVersion: ""
          objectAlias: db-connection-string
