apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug
  namespace: default
  labels:
    wiredbrain: debug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debug
  template:
    metadata:
      labels:
        app: debug
    spec:
      containers:
        - image: busybox
          name: debug
          command: ["sleep", "infinity"]
