apiVersion: v1
kind: Service
metadata:
  name: kube-explorer
  namespace: default
  labels:
    wiredbrain: kube-explorer
spec:
  ports:
    - port: 8019
      targetPort: http
  selector:
    app: kube-explorer
  type: LoadBalancer