apiVersion: v1
kind: Pod
metadata:
  name: test-runs-as-root
  namespace: default
spec:
  # Violates runAsNonRoot policy
  # Missing securityContext.runAsNonRoot: true
  containers:
  - name: api
    image: ghcr.io/wiredbrain/products-api:k8s-security-m2
    command: ["sleep", "infinity"]
