apiVersion: v1
kind: Pod
metadata:
  name: test-critical-cves
  namespace: default
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
  containers:
  - name: api
    # Violates CVE policy
    # Image contains known critical vulnerabilities
    image: ghcr.io/wiredbrain/products-api-bad:k8s-security-m2
    command: ["sleep", "infinity"]
