apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: least-privilege-binding
  namespace: wiredbrain
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view 
subjects:
- kind: User
  name: "least-privilege@wiredbrain.com" 
  apiGroup: rbac.authorization.k8s.io